version: '3.1'

services:

  mysql:
    container_name: simplepay
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: simplepay
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - simplepay_data_container:/data/db

volumes:
  simplepay_data_container: